### ISSUE TITLE
Help example for two_sample_viz() results in "Error: Must subset rows with a valid subscript vector."

### ISSUE THREAD

**Issue by bvancil** [astamm/flipr#2]
I tried the example from the help page for `two_sample_vis`:

``` r
library(flipr)
#> Warning: package 'flipr' was built under R version 4.0.4
x1 <- rnorm(10)
x2 <- rnorm(10, mean = 3)
null_spec <- function(y, parameters) {y - parameters[1]}
## Not run:
two_sample_viz(
  null_specification = null_spec,
  x = x1,
  y = x2,
  statistic = stat_t,
  B = 10000
)
#> i Setting the seed for sampling permutations
#> is mandatory for obtaining a continuous p-value
#> function. Using `seed = 1234`.
#> Error: Must subset rows with a valid subscript vector.
#> i Logical subscripts must match the size of the indexed input.
#> x Input has size 101 but subscript `r` has size 0.

## End(Not run)
```

<sup>Created on 2021-04-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by astamm** [comment]
Thanks for pointing that out. I am working on a new release with a finalized API for permutation inference which is a major refactoring of what I had done when you tested the code. I plan on submitting it to CRAN later this week. This issue should be resolved then.

**Comment by astamm** [comment]
This should be resolved with the new improved API. If you have a chance to try it out, I will appreciate any feedback. In the meantime, I am closing this issue.
